### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by hfduarte** [most-ieeta/SPT-DataLab#23]
I get a compilation error when trying to compile the application from source.
This happens when using both Netbeans 10 and 11.

The error is:
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-cli) on project sptdatalab-app: Compilation failure

ua/ieeta/sptdatalab/testbuilder/AppCorrGeometries.java:[947,23] cannot find symbol
symbol:   method transformOriginal(int,int,double,double)
location: variable coordUtils of type org.locationtech.jts.geom.CoordinateUtils
-> [Help 1]

The project builds and runs if I comment this line:
coordUtils.transformOriginal(appImage.getCurrentImageWidth(editPanel.isSecondPanel()),
                   appImage.getCurrentImageHeight(editPanel.isSecondPanel()), currImageWidthInPanel, currImageHeightInPanel);
in function
public List<Coordinate> transformToOriginalCoordinates(List<Coordinate> coordinates, GeometryEditPanel editPanel)
in class AppCorrGeometries.

**Comment by bsilva3** [comment]
I dont have that error. I am using netbeans 11. Make sure you clean and build the master project. Maybe there is some kind of conflict when you compile the project.

**Comment by hfduarte** [comment]
I looked at the problem further.

The JTS API in my system does not provide the function transformOriginal() for class org.locationtech.jts.geom.CoordinateUtils. Instead it provides the functions:
transform() and transformCoords(). They both achieve the same thing.

Since the app src uses the CoordinateUtils object instead of a new Coordinate the function I need to use is transformCoords().

The new code is:
coordUtils.transformCoords(appImage.getCurrentImageWidth(editPanel.isSecondPanel()),
                   appImage.getCurrentImageHeight(editPanel.isSecondPanel()), currImageWidthInPanel, currImageHeightInPanel);

now the application builds successfully.

I think the problem is a JTS version problem? That is, every time a user downloads the app and builds it it will get, possibly, a different version of the JTS library? If the JTS API has changed we may have a problem.

If this is the case, the app must force the use of a specific version of the JTS lib or provide it with the source code?

**Comment by bsilva3** [comment]
CoordinateUtils class was created when in development of SPTDataLab, and is not part of standard JTS, so it is not a JTS version problem.

What happens is that this class is inside module "core", and not inside module "app". If "core" module is not recompiled, the classes inside the "app" module cannot see the changes made to CoordinateUtils class.

I purposely changed one function of that class and clean and build both modules. The classes in app can't yet detect the changes i made. There should be a way to force these classes to see that CoordinatesUtils has changed (cleaning and building did not work, not even after rebuilding the master project).

The easiest solution is to move that class to the "app" module, and perhaps it makes sense since 
the class was developed for SPTDataLab.
